#!/usr/local/bin/bash

_common_setup() {
    load 'test_helper/bats-support/load'
    load 'test_helper/bats-assert/load'
    load 'test_helper/bats-mock/src/bats-mock.bash'
}

mock_commands() {
    declare -n map="$1"
    shift
    for command in "$@"; do
        declare mock="$(mock_create)"
        declare path_mocked_command="$BATS_TMPDIR/${command}"
        ln -sf "${mock}" "${path_mocked_command}"
        map["${command}"]="${mock}"
    done
    PATH="${mock%/*}:${PATH}"
}

unmock_commands() {
    for command in "$@"; do
        declare path_to_mocked_command="$BATS_TMPDIR/${command}"
        if [[ -e "${path_to_mocked_command}" ]]; then
            unlink "${path_to_mocked_command}"
        fi
    done
    PATH="${PATH/$BATS_TMPDIR:/}"
}
