#!/usr/local/bin/bash

_common_setup() {
    load 'test_helper/bats-support/load'
    load 'test_helper/bats-assert/load'
    load 'test_helper/bats-mock/src/bats-mock.bash'
}

mock_command() {
    mocked_command="$1"
    mock="$(mock_create)"
    mock_path="${mock%/*}"
    ln -sf "${mock}" "${mock_path}/${mocked_command}"
    PATH="${mock_path}/${mocked_command}:${PATH}"
}

unmock_command() {
    mock_path="${mock%/*}"
    mocked_command="$1"
    path_to_mocked_command="${mock_path}/${mocked_command}"
    if [[ -e "${path_to_mocked_command}" ]]; then
        unlink "${path_to_mocked_command}"
        #remove the prefix string added to PATH variable
        PATH="${PATH/path_to_mocked_command/}"
        echo "${PATH}"
    fi
}
