#!/usr/local/bin/bash

_common_setup() {
    load 'test_helper/bats-support/load'
    load 'test_helper/bats-assert/load'
    load 'test_helper/bats-mock/src/bats-mock.bash'
}

mock_commands() {
    # assume you want to mock every command passed as input
    declare -n map="$1"
    shift
    for command in "$@"; do
        local mock="$(mock_create)"
        local path_mocked_command="$BATS_TMPDIR/${command}"
        ln -sf "${mock}" "${path_mocked_command}"
        PATH="${path_mocked_command}:${PATH}"
        map["${command}"]="${mock}"
    done
}

unmock_commands() {
    for command in "$@"; do
        local path_to_mocked_command="$BATS_TMPDIR/${command}"
        if [[ -e "${path_to_mocked_command}" ]]; then
            unlink "${path_to_mocked_command}"
            #remove the string added to PATH variable
            PATH="${PATH/${path_to_mocked_command}:/}"
        fi
    done
}
