#!/usr/local/bin/bash

# Checks if the input argument is an integer
# meant to be used in a boolean context
check_if_integer() {
    if ! [[ "$1" =~ ^[0-9]+$ ]]; then
        exit 1
    else
        exit 0
    fi
}

check_if_integer "$@"
