#!/usr/local/bin/bash
# Script verifies the size of an input argument
# to determine if it falls within an accepted
# bound

# First positional parameter should be the argument
# being verified, and the second argument should be
# the inclusive low bound, and the third argument
# should be the inclusive high bound
if (($1 >= $2 && $1 <= $3)); then
    exit 0
else
    exit 1
fi
